site_name: Awesome
repo_url: https://github.com/bdura/cloud

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    # - navigation.tabs

nav:
  - index.md
  - Python:
    - python/index.md
    - python/ide.md
    - python/structure.md
    - python/documentation.md
  - Cloud:
    - cloud/index.md
    - cloud/installation.md
    - cloud/proxy.md
    - cloud/ip-address.md
    - cloud/reading-list.md
  - changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
