version: '3'

services:

  pypi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - "./packages:/app/packages"
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.pypi.rule=Host(`pypi.bdura.me`)
      - traefik.http.routers.pypi.entrypoints=https
      - traefik.http.routers.pypi.tls=true
      - traefik.http.routers.pypi.tls.certresolver=letsencrypt
      - traefik.http.routers.pypi.middlewares=admin-auth@file

networks:
  traefik-public:
    external: true
