version: '3'

services:

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    environment:
      VIRTUAL_HOST: portainer.bdura.me
      LETSENCRYPT_HOST: portainer.bdura.me
      VIRTUAL_PORT: 9000
    logging:
      options:
        tag: "{{.Name}}"

  grafana:
    image: grafana/grafana:8.2.2
    restart: unless-stopped
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      VIRTUAL_HOST: grafana.bdura.me
      LETSENCRYPT_HOST: grafana.bdura.me
    logging:
      options:
        tag: "{{.Name}}"

  loki:
    image: grafana/loki:2.3.0
    restart: unless-stopped
    container_name: loki
    ports:
      - 3100:3100
    command:
      - --config.file=/etc/loki/local-config.yml
    volumes:
      - ./configs/loki.yml:/etc/loki/local-config.yml
      - loki:/data/loki
    logging:
      options:
        tag: "{{.Name}}"

  # promtail:
  #   image: grafana/promtail:2.3.0
  #   container_name: promtail
  #   command: 
  #     - --config.file=/etc/promtail/promtail-config.yaml
  #   restart: unless-stopped
  #   volumes:
  #     - /var/log:/var/log:ro
  #     - ./configs/promtail.yml:/etc/promtail/promtail-config.yaml
  #   logging:
  #     options:
  #       tag: "{{.Name}}"

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    command: 
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    logging:
      options:
        tag: "{{.Name}}"
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=5d
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    logging:
      options:
        tag: "{{.Name}}"

  cadvisor:
    image: braingamer/cadvisor-arm:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    logging:
      options:
        tag: "{{.Name}}"

  # graphite:
  #   image: graphiteapp/graphite-statsd:latest
  #   container_name: graphite
  #   restart: unless-stopped
  #   ports:
  #     - "2003:2003"
  #     # - "2023-2024:2023-2024"
  #     # - "8125:8125/udp"
  #     # - "8126:8126"
  #   volumes:
  #     - graphite:/opt/graphite/storage
  #   logging:
  #     options:
  #       tag: "{{.Name}}"


networks:
  default:
    external:
      name: nginx

volumes:
  portainer-data:
  loki:
  grafana:
  # graphite:
