version: '3'

services:

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    environment:
      VIRTUAL_HOST: portainer.bdura.me
      LETSENCRYPT_HOST: portainer.bdura.me
      VIRTUAL_PORT: 9000


networks:
  default:
    external:
      name: nginx

volumes:
  portainer-data:
