global:
  sendAnonymousUsage: false

log:
  level: "INFO"
  format: "common"

accessLog: {}

metrics:
  prometheus: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    constraints: Label(`traefik.constraint-label`, `traefik-public`)
    swarmMode: false
    watch: true
  file:
    directory: /etc/traefik/config
    watch: true

api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "basile@bdura.me"
      storage: "/certificates/acme.json"
      tlsChallenge: {}
