version: '3'

services:

  vscode:
    image: codercom/code-server:latest
    container_name: vscode
    restart: unless-stopped
    user: $UID:$GID
    volumes:
      - ./config:/home/coder/.config
      - $HOME:/home/coder/project
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.vscode.rule=Host(`vscode.bdura.me`)
      - traefik.http.routers.vscode.entrypoints=https
      - traefik.http.routers.vscode.tls=true
      - traefik.http.routers.vscode.tls.certresolver=letsencrypt

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
