version: '3'

services:

docker run --name mattermost-preview -d --publish 8065:8065 --add-host dockerhost:127.0.0.1 mattermost/mattermost-preview


  nextcloud:
    image: mattermost/mattermost-preview
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ./volumes/instance:/var/www/html
      - ./volumes/apps:/var/www/html/custom_apps
      - ./volumes/config:/var/www/html/config
      - ./volumes/data:/var/www/html/data
    env_file:
      nextcloud.env
    environment:
      VIRTUAL_HOST: cloud.bdura.me
      LETSENCRYPT_HOST: cloud.bdura.me
      NEXTCLOUD_HOSTNAME: cloud.bdura.me
      POSTGRES_HOST: database:5432
      REDIS_HOST: redis
    logging:
      options:
        tag: "{{.Name}}"


networks:
  default:
    external:
      name: nginx
